favicon: null
name: Wired Up Technologies
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.9265233
  rhythmicContrast: 0.5
  brandColors:
    - '#FFFFFF'
    - '#DDDDDD'
    - '#797979'
    - '#FF9300'
    - '#B4B4B4'
  lightness: 0.8125
typography_spectrum: 0.41786
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
